#
# LED blink Waf script
#
from __future__ import print_function
import sys
sys.path.append('..')

rtems_version = "6"

try:
	# from ...rtems_waf import rtems as rtems
	import rtems_waf.rtems as rtems
except ImportError:
	print('error: no rtems_waf git submodule')
	import sys
	sys.exit(1)

def init(ctx):
	rtems.init(ctx, version = rtems_version, long_commands = True)

def bsp_configure(conf, arch_bsp):
	# Add BSP specific configuration checks
	pass

def options(opt):
	rtems.options(opt)

def configure(conf):
	rtems.configure(conf, bsp_configure = bsp_configure)

def build(bld):
	rtems.build(bld)
	bld(features = 'c cprogram', target = 'blinky.elf', cflags = '-g -O2', source = ['init.c'])
	bld(target= 'blinky.bin', source='blinky.elf', rule = '${OBJCOPY} -O binary ${SRC} ${TGT}')

